'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowRight, Bot, BookOpen, Dumbbell, Heart, Brain, Scale, Clock, Target, Flame } from 'lucide-react';

export default function TrainingPage() {
  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.5 }
  };

  const guides = [
    {
      category: 'Calisthenics Fundamentals',
      icon: <Dumbbell className="w-6 h-6" />,
      items: [
        'Calisthenics Fundamentals',
        'Progressive Overload',
        'Gymnastics vs Calisthenics',
        'Full Body vs Split',
        'Rest and Recovery',
        'Conditioning and Activation'
      ]
    },
    {
      category: 'Skill Paths',
      icon: <Target className="w-6 h-6" />,
      items: [
        'Push Skill Path',
        'Pull Skill Path',
        'Legs Skill Path'
      ]
    },
    {
      category: 'Training 101',
      icon: <BookOpen className="w-6 h-6" />,
      items: [
        'Beginner Workout Structure',
        'Intermediate Workout Structure',
        'Strengthening Your Core',
        'Leg Training'
      ]
    },
    {
      category: 'Skill Guides',
      icon: <Flame className="w-6 h-6" />,
      items: [
        'Handstand Guide',
        'Planche Guide',
        'Front Lever Guide'
      ]
    },
    {
      category: 'Nutrition',
      icon: <Heart className="w-6 h-6" />,
      items: [
        'General Nutrition',
        'Mass Gain vs Definition'
      ]
    },
    {
      category: 'Miscellaneous Guides',
      icon: <Brain className="w-6 h-6" />,
      items: [
        'Overcoming Plateaus',
        'Setting Realistic Goals'
      ]
    }
  ];

  return (
    <div className="container mx-auto px-4 py-12 space-y-16">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center"
      >
        <h1 className="text-5xl md:text-6xl font-bold mb-4 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
          Training
        </h1>
        <p className="text-lg text-foreground/70 max-w-3xl mx-auto">
          Your personalized calisthenics training powered by AI, or explore our comprehensive manual guides
        </p>
      </motion.div>

      {/* AI Training Interface - Placeholder */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="p-8 bg-gradient-to-br from-primary/10 to-secondary/10 border border-primary/30 rounded-2xl"
      >
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary/20 rounded-full mb-4">
            <Bot className="w-8 h-8 text-primary" />
          </div>
          <h2 className="text-3xl font-bold mb-2">AI-Powered Training</h2>
          <p className="text-foreground/70 max-w-2xl mx-auto">
            Get personalized workout plans generated by artificial intelligence based on your fitness level, goals, and available equipment.
          </p>
        </div>

        <div className="bg-card border border-border rounded-xl p-6 mb-6">
          <p className="text-warning text-center mb-4">
            ⚠️ AI Training requires OpenAI API setup. This feature is coming soon!
          </p>
          <p className="text-foreground/60 text-sm text-center">
            Once configured, you'll answer questions about your experience level, goals, and preferences, 
            and our AI will generate a customized training program for you.
          </p>
        </div>

        <div className="flex justify-center">
          <button className="px-8 py-4 bg-primary/50 cursor-not-allowed text-white/50 rounded-lg font-medium" disabled>
            AI Training - Coming Soon
          </button>
        </div>
      </motion.section>

      {/* Manual Training Guides */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
      >
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Manual Training Guides</h2>
          <p className="text-foreground/70">
            Don't want to use AI? Explore our comprehensive manual guides for structured training
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {guides.map((guide, index) => (
            <motion.div
              key={index}
              variants={fadeInUp}
              initial="initial"
              whileInView="animate"
              viewport={{ once: true }}
              className="p-6 bg-card border border-border rounded-xl hover:border-primary/50 transition-all duration-200"
            >
              <div className="text-primary mb-4">{guide.icon}</div>
              <h3 className="text-xl font-bold mb-4">{guide.category}</h3>
              <ul className="space-y-2">
                {guide.items.map((item, i) => (
                  <li key={i}>
                    <Link
                      href={`/training/${item.toLowerCase().replace(/\s+/g, '-').replace(/[()]/g, '').replace(/\./g, '')}`}
                      className="text-foreground/70 hover:text-primary transition-colors flex items-center gap-2 group"
                    >
                      <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                      {item}
                    </Link>
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* Quick Tips */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="p-8 bg-card border border-border rounded-2xl"
      >
        <h2 className="text-3xl font-bold mb-6 text-center">Quick Training Tips</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <Clock className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-bold mb-1">Rest Between Sets</h4>
                <p className="text-foreground/70 text-sm">Rest 2-3 minutes for strength work, 60-90 seconds for endurance</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <Target className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-bold mb-1">Progressive Overload</h4>
                <p className="text-foreground/70 text-sm">Gradually increase difficulty, reps, or time under tension</p>
              </div>
            </div>
          </div>
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <Scale className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-bold mb-1">Consistency Over Intensity</h4>
                <p className="text-foreground/70 text-sm">Train regularly rather than going all-out sporadically</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <Brain className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-bold mb-1">Listen to Your Body</h4>
                <p className="text-foreground/70 text-sm">Rest when needed and don't push through sharp pain</p>
              </div>
            </div>
          </div>
        </div>
      </motion.section>
    </div>
  );
}
